### ISSUE TITLE
dataclasses.field breaks doc generation

### ISSUE THREAD

**Issue by szemate** [pdoc3/pdoc#116]
If `dataclasses.field` is assigned as default value to a field in a class in the module documentation is generated for, doc generation breaks with `AttributeError`.

E.g. take the following module:
```py
from dataclasses import dataclass, field
from typing import Any, List

@dataclass
class C:
    mylist: List[Any] = field(default_factory=list)
```

### Expected Behavior
Successful doc generation

### Actual Behavior
```
Traceback (most recent call last):
  File "/home/szemate/.local/lib/python3.7/site-packages/pdoc/__init__.py", line 122, in _render_template
    return t.render(**config).strip()
  File "/usr/lib/python3.7/site-packages/mako/template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/szemate/.local/lib/python3.7/site-packages/pdoc/templates/html.mako", line 394, in render_body
    ${show_module(module)}
  File "/home/szemate/.local/lib/python3.7/site-packages/pdoc/templates/html.mako", line 0, in show_module
    
  File "/home/szemate/.local/lib/python3.7/site-packages/pdoc/templates/html.mako", line 178, in render_show_module
    params = ', '.join(c.params(annotate=show_type_annotations, link=link))
  File "/home/szemate/.local/lib/python3.7/site-packages/pdoc/__init__.py", line 900, in params
    annotate=annotate, link=link, module=self.module)
  File "/home/szemate/.local/lib/python3.7/site-packages/pdoc/__init__.py", line 1137, in _params
    p = safe_default_value(p)
  File "/home/szemate/.local/lib/python3.7/site-packages/pdoc/__init__.py", line 1110, in safe_default_value
    replacement = html.escape(replacement or p.default)
  File "/usr/lib64/python3.7/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
AttributeError: '_HAS_DEFAULT_FACTORY_CLASS' object has no attribute 'replace'
```

### Additional info

- pdoc version: 0.7.1

**Comment by kernc** [comment]
I think there might be a missing `repr()` call around `p.default` here:
https://github.com/pdoc3/pdoc/blob/1b644f6e86a5da4922679a8db540b83f8362ef08/pdoc/__init__.py#L1110

Can you check?

**Comment by szemate** [comment]
> Can you check?

It partly works; there is no exception, but the signature is duplicated in the docstring area:
![Opera Snapshot_2019-10-09_180506_localhost](https://user-images.githubusercontent.com/3908828/66503639-a0446200-eabf-11e9-9fca-9cb8220b12af.png)

**Comment by kernc** [comment]
Isn't that alright, since `C` has no docstring? That's the default docstring for `dataclass` objects.

Is there a `<factory>` HTML element in there after `=`? 🤨

**Comment by szemate** [comment]
> That's the default docstring for dataclass objects

Ah sorry, I didn't realise that. It's all fine then.
