### ISSUE TITLE
Uncaught exception when hiding documentation for inherited methods

### ISSUE THREAD

**Issue by huettenhain** [pdoc3/pdoc#125]
### Reproduce Behavior
Create a package named `test` with its `__init__.py` containing the following code:
```
class SuperClass:
    """The Super Class"""
    def Foo(self):
        """This is Foo"""
        pass

class SubClass(SuperClass):
    pass

__pdoc__ = {
    'SubClass.Foo': False
}
```
In the directory containing the folder `test`, run the following command:
```
pdoc --html test
```

### Expected Behavior
A documentation is created for the given module where the method `Foo` is documented for the class `SuperClass`, but not for the class `SubClass`.

### Actual Behavior
The following exception is thrown (on a Windows computer where `T:` represents the directory containing `test`:
```
Traceback (most recent call last):
  File "T:\venv\Scripts\pdoc-script.py", line 11, in <module>
    load_entry_point('pdoc3==0.7.2', 'console_scripts', 'pdoc')()
  File "T:\venv\lib\site-packages\pdoc\cli.py", line 450, in main
    pdoc.link_inheritance()
  File "T:\venv\lib\site-packages\pdoc\__init__.py", line 340, in link_inheritance
    module._link_inheritance()
  File "T:\venv\lib\site-packages\pdoc\__init__.py", line 665, in _link_inheritance
    c._link_inheritance()
  File "T:\venv\lib\site-packages\pdoc\__init__.py", line 994, in _link_inheritance
    dobj = self.doc[name]
KeyError: 'Foo'
```

**Comment by huettenhain** [comment]
Thanks! =)
