### ISSUE TITLE
ImportError since 0.7.3

### ISSUE THREAD

**Issue by denk-mal** [pdoc3/pdoc#157]
I have a small python app. (https://gitlab.com/denk_mal/das-keyboard-testlab)
and try to generate the doc in the main dir with `pdoc3 --html --force`.

### Expected Behavior
Up to 0.7.2 everything works fine

### Actual Behavior
Starting with 0.7.3 the generation fails with a stacktrace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pdoc/__init__.py", line 185, in import_module
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 121, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pdoc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/pdoc/cli.py", line 449, in main
    for module in args.modules]
  File "/usr/local/lib/python3.6/dist-packages/pdoc/cli.py", line 449, in <listcomp>
    for module in args.modules]
  File "/usr/local/lib/python3.6/dist-packages/pdoc/__init__.py", line 510, in __init__
    module = import_module(module)
  File "/usr/local/lib/python3.6/dist-packages/pdoc/__init__.py", line 187, in import_module
    raise ImportError('Error importing {!r}: {}'.format(module, e))
ImportError: Error importing '.': the 'package' argument is required to perform a relative import for '.'
```
### Steps to Reproduce

1. check out python project
2. change into the main dir
3. `pdoc3 --html --force`.

### Additional info

- pdoc version: 0.7.3

**Comment by kernc** [comment]
The regression was introduced in 6604a51205ce44c9886d834c46aeffd2dc09d8be.
