### ISSUE TITLE
Pdoc markdown issue

### ISSUE THREAD

**Issue by danihyunlee** [pdoc3/pdoc#234]
### Expected Behavior
I expected it to run over my module but I'm getting a markdown issue

### Actual Behavior
```
Traceback (most recent call last):
  File "/Users/spyder/anaconda3/bin/pdoc", line 505, in <module>
    html_out(module, args.html)
  File "/Users/spyder/anaconda3/bin/pdoc", line 342, in html_out
    source=not args.html_no_source)
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/pdoc/__init__.py", line 678, in html
    **kwargs)
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/mako/template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/mako/runtime.py", line 883, in _render
    **_kwargs_for_callable(callable_, data)
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "_html_mako", line 242, in render_body
  File "_html_mako", line 35, in show_module
  File "_html_mako", line 448, in render_show_module
  File "_html_mako", line 115, in mark
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/markdown/core.py", line 385, in markdown
    md = Markdown(**kwargs)
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/markdown/core.py", line 96, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/markdown/core.py", line 122, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/Users/spyder/anaconda3/lib/python3.7/site-packages/markdown/core.py", line 161, in build_extension
    module = importlib.import_module(ext_name)
  File "/Users/spyder/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'markdown.extensions.codehilite(linenums=False)'
```

### Steps to Reproduce

1. Run `pdoc --html src --html-dir docs --overwrite` over src folder once pythonpath set to directory containing src

### Additional info

- pdoc version:

**Comment by kernc** [comment]
What version pdoc3, what version markdown_py?
```bash
pdoc3 --version
markdown_py --version
```

**Comment by kernc** [comment]
I think reinstalling should help:
```bash
pip uninstall pdoc3
pip install pdoc3
```
If not, reopen.
