### ISSUE TITLE
Doesn't work with PyQt5: RuntimeError: wrapped C/C++ object of type QApplication has been deleted

### ISSUE THREAD

**Issue by jacobwilliams** [pdoc3/pdoc#285]
### Expected Behavior

I would like to be able to use pdoc3 for a project that imports [PyQt5](https://pypi.org/project/PyQt5/).

### Actual Behavior

It crashes.

### Steps to Reproduce

1. Consider this simple example:
```
example
|
|-- test.py
```

Where `test.py` is:

```python
""" Hello world """

from PyQt5.QtWidgets import *

def hello():
    """Hello"""
    print('hello')
```

2. Now run: `pdoc --html example`

The output is:

```
Traceback (most recent call last):
  File "\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "\anaconda3\Scripts\pdoc.exe\__main__.py", line 7, in <module>
  File "\anaconda3\lib\site-packages\pdoc\cli.py", line 539, in main
    for module in args.modules]
  File "\anaconda3\lib\site-packages\pdoc\cli.py", line 539, in <listcomp>
    for module in args.modules]
  File "\anaconda3\lib\site-packages\pdoc\__init__.py", line 681, in __init__
    context=self._context, skip_errors=skip_errors)
  File "\anaconda3\lib\site-packages\pdoc\__init__.py", line 630, in __init__
    for name, obj in inspect.getmembers(self.obj)
  File "\anaconda3\lib\site-packages\pdoc\__init__.py", line 632, in <listcomp>
    (is_from_this_module(obj) or name in var_docstrings))]
  File "\anaconda3\lib\site-packages\pdoc\__init__.py", line 626, in is_from_this_module
    mod = inspect.getmodule(inspect.unwrap(obj))
  File "\anaconda3\lib\inspect.py", line 511, in unwrap
    while _is_wrapper(func):
  File "\anaconda3\lib\inspect.py", line 502, in _is_wrapper
    return hasattr(f, '__wrapped__')
RuntimeError: wrapped C/C++ object of type QApplication has been deleted
```

This issue seems to occur for any file that includes PyQt5 imports.

### Additional info

- pdoc version: 0.9.1
- Anaconda Python: 3.7.3
- platform: Windows 10, 64 bit. 
- PyQt5 version: 5.12.2

**Comment by kernc** [comment]
I believe you could work around it by defining [`__all__`](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package).

**Comment by kernc** [comment]
An alternative as of https://github.com/pdoc3/pdoc/commit/9bdb076e267b33949fb6ffc906316e8651d5f474 would be to blacklist the offending object (i.e. `qApp`) with [`__pdoc__` dict](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__):
```py
# test.py:

from PyQt5.QtWidgets import *

__pdoc__ = {
    'qApp': False,
}

...
```
