### ISSUE TITLE
Favicon Errors

### ISSUE THREAD

**Issue by KyleKing** [pdoc3/pdoc#35]
### Description

pdoc3 throws errors that a `favicon.ico` file can't be found.

Is it up to the user to provide a favicon? If not, maybe there should be a default favicon.ico included with pdoc3? Or the error could be circumvented like in pdoc where they intentionally return None: [mitmproxy/pdoc/master/pdoc/web.py#L91-L93](https://github.com/mitmproxy/pdoc/blob/d27d9839b05cbf541336f83f832f7fc5e1495fb6/pdoc/web.py#L91-L93)

```py
    def html(self):
        """
        Retrieves and sends the HTML belonging to the path given in
        URL. This method is smart and will look for HTML files already
        generated and account for whether they are stale compared to
        the source code.
        """
        # Deny favico shortcut early.
        if self.path == "/favicon.ico":
            return None
        return pdoc.render.html_module(pdoc.extract.extract_module(self.import_path))
```

### Error Message

```sh
(base) 05:20 [PDOC] ¿ pdoc csv --http localhost:8000
Starting pdoc server on localhost:8000
pdoc server ready at http://localhost:8000
127.0.0.1 - - [24/Feb/2019 05:21:01] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2019 05:21:03] "GET /favicon.ico HTTP/1.1" 302 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50040)
Traceback (most recent call last):
  File "/Users/kyleking/anaconda3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/kyleking/anaconda3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Users/kyleking/anaconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/kyleking/anaconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/kyleking/anaconda3/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/Users/kyleking/anaconda3/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/cli.py", line 175, in do_GET
    out = self.html()
  File "/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/cli.py", line 205, in html
    return pdoc.html(self.import_path_from_req_url, http_server=True)
  File "/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/__init__.py", line 471, in html
    mod = Module(import_module(module_name), docfilter=docfilter)
  File "/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/__init__.py", line 526, in import_module
    raise ValueError('File or module {!r} not found'.format(module))
ValueError: File or module 'favicon.ico' not found
----------------------------------------
127.0.0.1 - - [24/Feb/2019 05:21:07] "GET /csv HTTP/1.1" 302 -
/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/__init__.py:585: UserWarning: Couldn't get/parse source of '<Class 'csv.Error'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
127.0.0.1 - - [24/Feb/2019 05:21:07] "GET /csv/ HTTP/1.1" 200 -
127.0.0.1 - - [24/Feb/2019 05:21:07] "GET /favicon.ico HTTP/1.1" 302 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50102)
Traceback (most recent call last):
  File "/Users/kyleking/anaconda3/lib/python3.7/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/Users/kyleking/anaconda3/lib/python3.7/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/Users/kyleking/anaconda3/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/kyleking/anaconda3/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/Users/kyleking/anaconda3/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/Users/kyleking/anaconda3/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/cli.py", line 175, in do_GET
    out = self.html()
  File "/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/cli.py", line 205, in html
    return pdoc.html(self.import_path_from_req_url, http_server=True)
  File "/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/__init__.py", line 471, in html
    mod = Module(import_module(module_name), docfilter=docfilter)
  File "/Users/kyleking/anaconda3/lib/python3.7/site-packages/pdoc/__init__.py", line 526, in import_module
    raise ValueError('File or module {!r} not found'.format(module))
ValueError: File or module 'favicon.ico' not found
```

### Steps to Reproduce

1. Run `pdoc csv --http localhost:8000`

### Additional info

- pdoc version: 0.5.2
- OS: Mac OS Mojave 10.14.3
- Python 3.7.2 (Anaconda)

**Comment by kernc** [comment]
Pdoc3 still uses this code.
https://github.com/pdoc3/pdoc/blob/24a561ceef1b96575e818504869abc0b5b44589d/pdoc/cli.py#L193-L205
It's a bug. PR welcome.

**Comment by kernc** [comment]
@KyleKing, care to tackle this one as well?

**Comment by KyleKing** [comment]
Yeah of course! I also may have found another bug that I’ll open an issue for when I’m back from work tonight

**Comment by kernc** [comment]
Sorry, I considered https://github.com/pdoc3/pdoc/commit/1e0608f7d9d71e458ec283eedd75fbb009649196 a better fix, which further avoids the needless `/favicon.ico/` redirect that took place already in `do_GET()` method. Thanks for the report though!

What's the other issue?

**Comment by KyleKing** [comment]
Yeah, it is a more efficient fix!

There is a minor issue on Windows with html linking for module files. I need to borrow my girlfriend’s PC this weekend to test it out and I’ll post an issue once I have a clean way to replicate it
