### ISSUE TITLE
Cyclic dependency when class derived from namedtuple

### ISSUE THREAD

**Issue by rysson** [pdoc3/pdoc#78]
### Expected Behavior

Generate documentation.

### Actual Behavior

```
Traceback (most recent call last):
  File "/tmp/zz-7EQ2Br1/.venv/bin/pdoc", line 11, in <module>
    load_entry_point('pdoc3==0.6.3', 'console_scripts', 'pdoc')()
  File "/tmp/zz-7EQ2Br1/.venv/lib/python3.7/site-packages/pdoc/cli.py", line 443, in main
    pdoc.link_inheritance()
  File "/tmp/zz-7EQ2Br1/.venv/lib/python3.7/site-packages/pdoc/__init__.py", line 354, in link_inheritance
    for cls in _toposort(graph):
  File "/tmp/zz-7EQ2Br1/.venv/lib/python3.7/site-packages/pdoc/__init__.py", line 336, in _toposort
    assert not graph, "A cyclic dependency exists amongst %r" % graph
AssertionError: A cyclic dependency exists amongst {<Class 'a.Location'>: {<Class 'a.Location'>}}
```

### Steps to Reproduce

1. Create `a.py`:
```python
from collections import namedtuple

class Location(namedtuple('Location', ['lat', 'lon'])):
    """Geo-location, GPS position."""
```

2. Run `pdoc3 --html a.py`

### Additional info

- pdoc version: 0.6.3
- Python 3.7.3

**Comment by rysson** [comment]
O guess, reason is use `Location` as tuple name and as class name. When I rename anything, everything is OK, as follow:

```python
from collections import namedtuple

class Location(namedtuple('LocationTuple', ['lat', 'lon'])):
    """Geo-location, GPS position."""
```

**Comment by kernc** [comment]
It likely doesn't affect a lot of users, but it sure is a bug. Thanks! :+1:
